name: gc4dgs
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aom=3.9.1=hac33072_0
  - blas=2.14=openblas
  - brotli-python=1.1.0=py38h17151c0_1
  - bzip2=1.0.8=hd590300_5
  - ca-certificates=2024.12.14=hbcca054_0
  - cairo=1.18.0=h3faef2a_0
  - certifi=2024.8.30=py38h06a4308_0
  - cffi=1.17.1=py38h1fdaa30_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - cudatoolkit=11.6.2=hfc3e2af_13
  - dav1d=1.2.1=h5eee18b_0
  - expat=2.6.4=h6a678d5_0
  - ffmpeg=7.0.1=gpl_hb399a10_100
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - freetype=2.12.1=h267a509_2
  - fribidi=1.0.10=h7b6447c_0
  - future=1.0.0=pyhd8ed1ab_0
  - gettext=0.22.5=he02047a_3
  - gettext-tools=0.22.5=he02047a_3
  - gmp=6.3.0=h59595ed_1
  - gnutls=3.7.9=hb077bed_0
  - graphite2=1.3.14=h295c915_1
  - harfbuzz=8.5.0=hfac3d4d_0
  - icu=73.2=h59595ed_0
  - idna=3.7=pyhd8ed1ab_0
  - intel-openmp=2022.1.0=h9e868ea_3769
  - jpeg=9e=h0b41bf4_3
  - lame=3.100=h166bdaf_1003
  - lcms2=2.14=h6ed2654_0
  - ld_impl_linux-64=2.40=h55db66e_0
  - lerc=4.0.0=h27087fc_0
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libasprintf=0.22.5=he8f35ee_3
  - libasprintf-devel=0.22.5=he8f35ee_3
  - libass=0.17.1=h8fe9dca_1
  - libblas=3.8.0=14_openblas
  - libcblas=3.8.0=14_openblas
  - libdeflate=1.14=h166bdaf_0
  - libdrm=2.4.124=hb9d3cd8_0
  - libexpat=2.6.4=h5888daf_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.1.0=h77fa898_1
  - libgcc-ng=14.1.0=h69a702a_1
  - libgettextpo=0.22.5=he02047a_3
  - libgettextpo-devel=0.22.5=he02047a_3
  - libgfortran-ng=7.5.0=h14aa051_20
  - libgfortran4=7.5.0=h14aa051_20
  - libglib=2.80.2=hf974151_0
  - libgomp=14.1.0=h77fa898_1
  - libhwloc=2.11.2=default_h0d58e46_1001
  - libiconv=1.17=hd590300_2
  - libidn2=2.3.7=hd590300_0
  - liblapack=3.8.0=14_openblas
  - liblapacke=3.8.0=14_openblas
  - libopenblas=0.3.7=h5ec1e0e_6
  - libopenvino=2024.1.0=h2da1b83_7
  - libopenvino-auto-batch-plugin=2024.1.0=hb045406_7
  - libopenvino-auto-plugin=2024.1.0=hb045406_7
  - libopenvino-hetero-plugin=2024.1.0=h5c03a75_7
  - libopenvino-intel-cpu-plugin=2024.1.0=h2da1b83_7
  - libopenvino-intel-gpu-plugin=2024.1.0=h2da1b83_7
  - libopenvino-intel-npu-plugin=2024.1.0=he02047a_7
  - libopenvino-ir-frontend=2024.1.0=h5c03a75_7
  - libopenvino-onnx-frontend=2024.1.0=h07e8aee_7
  - libopenvino-paddle-frontend=2024.1.0=h07e8aee_7
  - libopenvino-pytorch-frontend=2024.1.0=he02047a_7
  - libopenvino-tensorflow-frontend=2024.1.0=h39126c6_7
  - libopenvino-tensorflow-lite-frontend=2024.1.0=he02047a_7
  - libopus=1.3.1=h5eee18b_1
  - libpciaccess=0.18=hd590300_0
  - libpng=1.6.43=h2797004_0
  - libprotobuf=4.25.3=he621ea3_0
  - libsqlite=3.45.3=h2797004_0
  - libstdcxx=14.1.0=hc0a3c3a_1
  - libstdcxx-ng=13.2.0=hc0a3c3a_7
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.4.0=h82bc61c_5
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=2.38.1=h0b41bf4_0
  - libva=2.21.0=h4ab18f5_2
  - libvpx=1.14.1=hac33072_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.15=h7f8727e_0
  - libxml2=2.13.5=hfdd30dd_0
  - libzlib=1.2.13=hd590300_5
  - mkl=2020.2=256
  - ncurses=6.5=h59595ed_0
  - nettle=3.9.1=h7ab15ed_0
  - ninja=1.12.1=h297d8ca_0
  - numpy=1.22.4=py38h99721a1_0
  - ocl-icd=2.3.2=h5eee18b_1
  - openh264=2.4.1=h59595ed_0
  - openjpeg=2.5.0=h7d73246_1
  - openssl=3.4.0=hb9d3cd8_0
  - p11-kit=0.24.1=hc5aa10d_0
  - pcre2=10.43=hcad00b1_0
  - pillow=10.4.0=py38h5eee18b_0
  - pip=22.3.1=pyhd8ed1ab_0
  - pixman=0.44.2=h29eaf8c_0
  - plyfile=0.8.1=pyhd8ed1ab_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pugixml=1.14=h59595ed_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.20=he870216_0
  - python_abi=3.8=2_cp38
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.2=py38h2019614_0
  - readline=8.2=h8228510_1
  - requests=2.31.0=pyhd8ed1ab_0
  - setuptools=69.0.3=pyhd8ed1ab_0
  - snappy=1.2.1=h6a678d5_0
  - sqlite=3.45.3=h2c6b66d_0
  - svt-av1=2.1.0=hac33072_0
  - tbb=2022.0.0=hceb3a55_0
  - tk=8.6.14=h39e8969_0
  - torchaudio=0.12.1=py38_cu116
  - urllib3=2.2.1=pyhd8ed1ab_0
  - wheel=0.42.0=pyhd8ed1ab_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xorg-fixesproto=5.0=hb9d3cd8_1003
  - xorg-kbproto=1.0.7=hb9d3cd8_1003
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.5=he73a12e_0
  - xorg-libx11=1.8.9=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-renderproto=0.11.1=hb9d3cd8_1003
  - xorg-xextproto=7.3.0=hb9d3cd8_1004
  - xorg-xproto=7.0.31=h27cfd23_1007
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - absl-py==2.1.0
      - addict==2.4.0
      - aiofiles==23.2.1
      - altair==5.4.1
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.5.0
      - asttokens==2.4.1
      - astunparse==1.6.3
      - attrs==24.2.0
      - backcall==0.2.0
      - blinker==1.8.2
      - cachetools==5.5.0
      - click==8.1.7
      - colorama==0.4.6
      - comm==0.2.2
      - configargparse==1.7
      - contourpy==1.1.1
      - cycler==0.12.1
      - dash==2.18.1
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - decorator==5.1.1
      - dill==0.3.9
      - exceptiongroup==1.2.2
      - executing==2.1.0
      - fastapi==0.115.0
      - fastjsonschema==2.20.0
      - ffmpy==0.4.0
      - filelock==3.16.1
      - flask==3.0.3
      - fonttools==4.54.1
      - fsspec==2024.9.0
      - fvcore==0.1.6
      - google-auth==2.35.0
      - google-auth-oauthlib==1.0.0
      - gradio==4.29.0
      - gradio-client==0.16.1
      - gradio-imageslider==0.0.18
      - grpcio==1.66.2
      - h11==0.14.0
      - httpcore==1.0.6
      - httpx==0.27.2
      - huggingface-hub==0.25.1
      - imageio==2.35.1
      - imagesize==1.4.1
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - iopath==0.1.10
      - ipython==8.12.3
      - ipywidgets==8.1.5
      - itsdangerous==2.2.0
      - jedi==0.19.1
      - jinja2==3.1.4
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter-core==5.7.2
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.7
      - kornia==0.7.3
      - kornia-rs==0.1.5
      - lazy-loader==0.4
      - lightning-utilities==0.11.7
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mpmath==1.3.0
      - narwhals==1.9.1
      - natsort==8.4.0
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.1
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - open3d==0.18.0
      - opencv-python==4.10.0.84
      - orjson==3.10.7
      - packaging==24.1
      - pandas==2.0.3
      - parso==0.8.4
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pkgutil-resolve-name==1.3.10
      - platformdirs==4.3.6
      - plotly==5.24.1
      - pointops2==1.0
      - portalocker==3.0.0
      - prompt-toolkit==3.0.48
      - protobuf==5.28.2
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pydub==0.25.1
      - pygments==2.18.0
      - pyparsing==3.1.4
      - pyquaternion==0.9.9
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.12
      - pytorch3d==0.7.3
      - pytz==2024.2
      - pywavelets==1.4.1
      - referencing==0.35.1
      - requests-oauthlib==2.0.0
      - retrying==1.3.4
      - rich==13.9.2
      - rpds-py==0.20.0
      - rsa==4.9
      - ruff==0.6.9
      - safetensors==0.4.5
      - scikit-image==0.21.0
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - semantic-version==2.10.0
      - shellingham==1.5.4
      - simple-knn==0.0.0
      - six==1.16.0
      - sniffio==1.3.1
      - stack-data==0.6.3
      - starlette==0.38.6
      - sympy==1.13.3
      - tabulate==0.9.0
      - taichi==1.7.2
      - tenacity==9.0.0
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - termcolor==2.4.0
      - threadpoolctl==3.5.0
      - tifffile==2023.7.10
      - timm==1.0.9
      - tomlkit==0.12.0
      - torch==2.1.2+cu118
      - torchmetrics==1.4.2
      - torchvision==0.16.2+cu118
      - tqdm==4.66.5
      - traitlets==5.14.3
      - triton==2.1.0
      - typer==0.12.5
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - uvicorn==0.31.0
      - wcwidth==0.2.13
      - websockets==11.0.3
      - werkzeug==3.0.4
      - widgetsnbextension==4.0.13
      - yacs==0.1.8
      - zipp==3.20.2
