gaussian_dim: 4
time_duration: [0.0, 10.0]
num_pts: 300_000
num_pts_ratio: 1.0
rot_4d: True
force_sh_3d: False
batch_size: 4
exhaust_test: True

ModelParams:
  sh_degree: 3
  source_path: "data/enerf/actor1"
  model_path: "output/enerf/actor1"
  images: "images"
  resolution: 1
  white_background: False
  data_device: "cuda"
  eval: True
  extension: ".png"
  num_extra_pts: 0
  loaded_pth: ""
  frame_ratio: 1
  dataloader: True                  # dataloader改为False意味着加载GT图片用于估计GT深度图,此时需要修改utils/camera_utils.py的61-62行代码

PipelineParams:                     # 修改PipelineParams时，arguments/__init__.py中的PipelineParams对应部分也需要修改（运行render.py时）。
  convert_SHs_python: False
  compute_cov3D_python: False
  debug: False
  env_map_res: 0
  env_optimize_until: 1000000000
  env_optimize_from: 0
  eval_shfs_4d: True

OptimizationParams:
  iterations: 10_000
  position_lr_init: 0.00016
  position_t_lr_init: -1.0
  position_lr_final: 0.0000016
  position_lr_delay_mult: 0.01
  position_lr_max_steps: 30_000
  feature_lr: 0.0025
  opacity_lr: 0.05
  scaling_lr: 0.005
  rotation_lr: 0.001
  percent_dense: 0.01
  lambda_dssim: 0.2
  thresh_opa_prune: 0.005                 # thresh_opa_prune 0.005
  densification_interval: 200             # densification_interval
  opacity_reset_interval: 30_000          # opacity_reset_interval
  densify_from_iter: 500
  densify_until_iter: 7_000               # densify_until_iter
  densify_grad_threshold: 0.0006          # densify_grad_threshold
  densify_grad_t_threshold: 0.0006 / 40   # densify_grad_t_threshold
  densify_until_num_points: -1
  final_prune_from_iter: -1
  sh_increase_interval: 1000
  lambda_opa_mask: 0.0
  lambda_rigid: 0.0
  lambda_motion: 0.0
  dist_thres: 10                        # dist_thres
  depth_weight: 0.020                   # depth_weight        
  start_sample_pseudo: 2500             # start_sample_pseudo
  end_sample_pseudo: 5000               # end_sample_pseudo
  sample_pseudo_interval: 10            # sample_pseudo_interval
  depth_pseudo_weight: 0.010            # depth_pseudo_weight