gaussian_dim: 4
time_duration: [0.0, 10.0]
num_pts: 300_000
num_pts_ratio: 1.0
rot_4d: True
force_sh_3d: False
batch_size: 4
exhaust_test: True
scale_factor: 1.0 

ModelParams:
  sh_degree: 3
  source_path: "data/dynerf/flame_salmon/3_views"
  model_path: "output/dynerf/flame_salmon/3_views/MVS"
  images: "images"
  resolution: 1
  white_background: False
  data_device: "cuda"
  eval: True
  extension: ".png"
  num_extra_pts: 0
  loaded_pth: ""
  frame_ratio: 1
  dataloader: True                    

PipelineParams:                      
  convert_SHs_python: False
  compute_cov3D_python: False
  debug: False
  env_map_res: 0
  env_optimize_until: 1000000000
  eval_shfs_4d: True

OptimizationParams:
  iterations: 15_000
  position_lr_init: 0.00016
  position_t_lr_init: -1.0
  position_lr_final: 0.000001610
  feature_lr: 0.0025
  opacity_lr: 0.05
  scaling_lr: 0.005
  rotation_lr: 0.001
  percent_dense: 0.01
  lambda_dssim: 0.2
  thresh_opa_prune: 0.005              
  densification_interval: 150          
  opacity_reset_interval: 30_000     
  densify_from_iter: 500
  densify_until_iter: 6_000             
  densify_grad_threshold: 0.0006      
  densify_grad_t_threshold: 0.0006 / 40   
  densify_until_num_points: -1
  final_prune_from_iter: -1
  sh_increase_interval: 1000
  lambda_opa_mask: 0.0005
  lambda_rigid: 0.0
  lambda_motion: 0.0
  dist_thres: 10                      
  depth_ordinal_weight: 0.05           
  depth_patch_weight: 0.02
  depth_mvs_weight: 0.02                
  start_sample_pseudo: 2500            
  end_sample_pseudo: 5000              
  sample_pseudo_interval: 10           
  depth_pseudo_weight: 0.010         